# 开发环境 ZhiTan 覆盖配置
server:
  port: 9050
  servlet:
    context-path: /

ruoyi:
  demoEnabled: true
  captchaType: math
  profile: ./uploadPath

logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

user:
  password:
    maxRetryCount: 5
    lockTime: 10

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.h2.Driver
    druid:
      master:
        url: jdbc:h2:mem:ruoyi;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=VALUE,SYSDATE;BUILTIN_ALIAS_OVERRIDE=TRUE;INIT=CREATE ALIAS IF NOT EXISTS sysdate FOR 'com.ruoyi.common.utils.DateUtils.getNowDate'
        username: sa
        password: ""
        driverClassName: org.h2.Driver
      slave:
        enabled: false
        url:
        username:
        password:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      connectTimeout: 30000
      socketTimeout: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.ruoyi.**.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    banner: false
    refresh: true
    db-config:
      id-type: auto
      field-strategy: not_empty
      db-column-underline: true
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql

influxdb:
  host: http://127.0.0.1:8086
  token: 1OB7JfUX-1DdF4yFleVxqRJpfx68FK177A==
  org: pv
  bucket: pvdata
  measurement: pv

wx:
  appid: wx
  secret: abc
  token: demo-token
  encodingAesKey: demo-encoding-aes-key
  page: pages/index/index
  template_id: demo-template-id
  env_version: "develop"

alarm:
  offline: 1
